# Generated by Django 5.2.2 on 2025-06-11 11:15

import django.db.models.deletion
import projeto.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                (
                    "registration_number",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Número de Registro",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Nome Completo"),
                ),
                (
                    "phone_number_aluno",
                    models.CharField(
                        max_length=15,
                        validators=[projeto.models.validate_phone],
                        verbose_name="Nº do celular (--) ---- ---- do aluno",
                    ),
                ),
                (
                    "email_aluno",
                    models.CharField(max_length=100, verbose_name="Email do aluno"),
                ),
                (
                    "cpf_aluno",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[projeto.models.validate_cpf],
                        verbose_name="CPF do aluno",
                    ),
                ),
                ("birthday_aluno", models.DateField()),
                (
                    "class_choices",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1A", "1º Ano A"),
                            ("1B", "1º Ano B"),
                            ("1C", "1º Ano C"),
                            ("2A", "2º Ano A"),
                            ("2B", "2º Ano B"),
                            ("2C", "2º Ano C"),
                            ("3A", "3º Ano A"),
                            ("3B", "3º Ano B"),
                            ("3C", "3º Ano C"),
                        ],
                        max_length=2,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Materia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Nome da Matéria"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Agenda",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100, verbose_name="Título")),
                ("descricao", models.TextField(verbose_name="Descrição")),
                ("data_evento", models.DateField(verbose_name="Data do Evento")),
                (
                    "arquivo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="agenda_files/",
                        verbose_name="Arquivo",
                    ),
                ),
                (
                    "lembrete",
                    models.BooleanField(default=False, verbose_name="Lembrete Ativado"),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Livro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "titulo",
                    models.CharField(max_length=200, verbose_name="Título do Livro"),
                ),
                ("autor", models.CharField(max_length=100, verbose_name="Autor")),
                ("resumo", models.TextField(verbose_name="Resumo")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("disponivel", "Disponível"),
                            ("em_uso", "Em Uso"),
                            ("fora_de_estoque", "Fora de Estoque"),
                            ("indisponivel", "Indisponível"),
                        ],
                        default="disponivel",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "usuario_em_uso",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Usuário em Uso",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Presenca",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField(verbose_name="Data")),
                (
                    "status",
                    models.CharField(
                        choices=[("F", "Falta"), ("P", "Presente")],
                        max_length=1,
                        verbose_name="Status",
                    ),
                ),
                (
                    "observacao",
                    models.TextField(blank=True, null=True, verbose_name="Observação"),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.aluno",
                        verbose_name="Aluno",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Professor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=50, verbose_name="Nome")),
                (
                    "last_name",
                    models.CharField(max_length=50, verbose_name="Sobrenome"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15, verbose_name="Nº do celular (--) ---- ----"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=100, verbose_name="Email do professor"
                    ),
                ),
                ("address", models.CharField(max_length=100, verbose_name="Endereço")),
                (
                    "cpf",
                    models.CharField(
                        max_length=11, unique=True, verbose_name="CPF do professor"
                    ),
                ),
                (
                    "registration_number",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Número de Registro"
                    ),
                ),
                (
                    "materias",
                    models.ManyToManyField(
                        blank=True,
                        related_name="professores_responsaveis",
                        to="projeto.materia",
                        verbose_name="Matérias",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="materia",
            name="professor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="materias_responsaveis",
                to="projeto.professor",
                verbose_name="Professor Responsável",
            ),
        ),
        migrations.CreateModel(
            name="Responsavel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=50, verbose_name="Nome do responsável"),
                ),
                (
                    "last_name",
                    models.CharField(
                        max_length=50, verbose_name="Sobrenome do responsável"
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        max_length=15,
                        validators=[projeto.models.validate_phone],
                        verbose_name="Nº do celular (--) ---- ---- do responsável",
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        max_length=100, verbose_name="Email do responsável"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        max_length=100, verbose_name="Endereço do responsável"
                    ),
                ),
                (
                    "cpf",
                    models.CharField(
                        max_length=11,
                        unique=True,
                        validators=[projeto.models.validate_cpf],
                        verbose_name="CPF do responsável",
                    ),
                ),
                ("birthday", models.DateField()),
                (
                    "alunos",
                    models.ManyToManyField(
                        blank=True,
                        related_name="responsaveis",
                        to="projeto.aluno",
                        verbose_name="Alunos do Responsável",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="aluno",
            name="responsavel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Aluno",
                to="projeto.responsavel",
                verbose_name="Responsável",
            ),
        ),
        migrations.CreateModel(
            name="Turma",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "turma",
                    models.CharField(
                        choices=[
                            ("1A", "1º Ano A"),
                            ("1B", "1º Ano B"),
                            ("1C", "1º Ano C"),
                            ("2A", "2º Ano A"),
                            ("2B", "2º Ano B"),
                            ("2C", "2º Ano C"),
                            ("3A", "3º Ano A"),
                            ("3B", "3º Ano B"),
                            ("3C", "3º Ano C"),
                        ],
                        max_length=2,
                        verbose_name="Turma",
                    ),
                ),
                (
                    "materia_1",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turma_materia_1",
                        to="projeto.materia",
                        verbose_name="Matéria 1",
                    ),
                ),
                (
                    "materia_2",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turma_materia_2",
                        to="projeto.materia",
                        verbose_name="Matéria 2",
                    ),
                ),
                (
                    "materia_3",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turma_materia_3",
                        to="projeto.materia",
                        verbose_name="Matéria 3",
                    ),
                ),
                (
                    "materia_4",
                    models.ForeignKey(
                        blank=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="turma_materia_4",
                        to="projeto.materia",
                        verbose_name="Matéria 4",
                    ),
                ),
                (
                    "padrinho",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="turmas_padrinhadas",
                        to="projeto.professor",
                        verbose_name="Padrinho",
                    ),
                ),
                (
                    "representante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="representante_turma",
                        to="projeto.aluno",
                        verbose_name="Representante",
                    ),
                ),
                (
                    "vice_representante",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vice_representante_turma",
                        to="projeto.aluno",
                        verbose_name="Vice-Representante",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DesempenhoAcademico",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "bimestre_1",
                    models.FloatField(default=0, verbose_name="Nota 1º Bimestre"),
                ),
                (
                    "bimestre_2",
                    models.FloatField(default=0, verbose_name="Nota 2º Bimestre"),
                ),
                (
                    "bimestre_3",
                    models.FloatField(default=0, verbose_name="Nota 3º Bimestre"),
                ),
                (
                    "bimestre_4",
                    models.FloatField(default=0, verbose_name="Nota 4º Bimestre"),
                ),
                (
                    "media_final",
                    models.FloatField(editable=False, verbose_name="Média Final"),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.aluno",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.materia",
                        verbose_name="Matéria",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.turma",
                        verbose_name="Turma",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Contrato",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email_responsavel",
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name="Email do Responsável",
                    ),
                ),
                (
                    "signed_contract",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="signed_contracts/",
                        verbose_name="Contrato Assinado",
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.aluno",
                        verbose_name="Nome do Aluno",
                    ),
                ),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.responsavel",
                        verbose_name="Nome do Responsável",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.turma",
                        verbose_name="Turma/Itinerário",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Nota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nota_presenca",
                    models.FloatField(
                        default=0,
                        validators=[projeto.models.validate_nota],
                        verbose_name="Nota de Presença (Diário)",
                    ),
                ),
                (
                    "nota_atividade",
                    models.FloatField(
                        default=0,
                        validators=[projeto.models.validate_nota],
                        verbose_name="Nota de Atividade (Diário)",
                    ),
                ),
                (
                    "nota_avaliativa",
                    models.FloatField(
                        default=0,
                        validators=[projeto.models.validate_nota],
                        verbose_name="Nota Avaliativa (Mensal)",
                    ),
                ),
                (
                    "nota_final",
                    models.FloatField(
                        editable=False, verbose_name="Nota Final (0 a 100)"
                    ),
                ),
                (
                    "aluno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.aluno",
                        verbose_name="Aluno",
                    ),
                ),
                (
                    "materia",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.materia",
                        verbose_name="Matéria",
                    ),
                ),
                (
                    "turma",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="projeto.turma",
                        verbose_name="Turma",
                    ),
                ),
            ],
            options={
                "unique_together": {("turma", "materia", "aluno")},
            },
        ),
    ]
