# Generated by Django 5.2.2 on 2025-06-11 12:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("projeto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aluno",
            name="user_group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aluno_group",
                to="auth.group",
                verbose_name="Grupo do Aluno",
            ),
        ),
        migrations.AddField(
            model_name="professor",
            name="user_group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="professor_group",
                to="auth.group",
                verbose_name="Grupo do Professor",
            ),
        ),
        migrations.AddField(
            model_name="responsavel",
            name="user_group",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responsavel_group",
                to="auth.group",
                verbose_name="Grupo do Responsável",
            ),
        ),
    ]
