# Generated by Django 5.2.2 on 2025-06-11 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("projeto", "0002_aluno_user_group_professor_user_group_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aluno",
            name="user_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auth.group",
            ),
        ),
    ]
